import '../models/models.dart';

class FakeClinicDatabase {
  static List<Patient> getSamplePatients() {
    final now = DateTime.now();

    return [
      Patient(
        id: 'PAT-1001',
        name: 'Rajesh Sharma',
        phone: '9876543210',
        age: 45,
        gender: 'Male',
        address: 'House No. 42, Green Park, New Delhi',
        medicalHistory: 'Hypertension (5 yrs), Seasonal Dust Allergy',
        createdAt: now.subtract(const Duration(days: 60)),
      ),
      Patient(
        id: 'PAT-1002',
        name: 'Priya Ananth',
        phone: '9123456789',
        age: 32,
        gender: 'Female',
        address: 'Flat 304, Sunshine Apts, Indiranagar, Bengaluru',
        medicalHistory: 'Migraine, Vitamin D Deficiency',
        createdAt: now.subtract(const Duration(days: 45)),
      ),
      Patient(
        id: 'PAT-1003',
        name: 'Amit Patel',
        phone: '9988776655',
        age: 58,
        gender: 'Male',
        address: '12, Shanti Enclave, Navrangpura, Ahmedabad',
        medicalHistory: 'Type 2 Diabetes Mellitus, Mild Osteoarthritis',
        createdAt: now.subtract(const Duration(days: 30)),
      ),
      Patient(
        id: 'PAT-1004',
        name: 'Sunita Verma',
        phone: '9445566778',
        age: 28,
        gender: 'Female',
        address: 'Sector 8, Malviya Nagar, Jaipur',
        medicalHistory: 'No chronic illness. Allergic to Sulfa drugs',
        createdAt: now.subtract(const Duration(days: 20)),
      ),
      Patient(
        id: 'PAT-1005',
        name: 'Vikram Singh',
        phone: '9811223344',
        age: 50,
        gender: 'Male',
        address: '77, Model Town, Ludhiana',
        medicalHistory: 'Hyperlipidemia, Chronic Back Pain',
        createdAt: now.subtract(const Duration(days: 15)),
      ),
      Patient(
        id: 'PAT-1006',
        name: 'Ananya Gupta',
        phone: '9765432109',
        age: 24,
        gender: 'Female',
        address: 'B-12, Salt Lake Sector 1, Kolkata',
        medicalHistory: 'Bronchial Asthma (Uses Salbutamol Inhaler)',
        createdAt: now.subtract(const Duration(days: 10)),
      ),
      Patient(
        id: 'PAT-1007',
        name: 'Suresh Menon',
        phone: '9847012345',
        age: 63,
        gender: 'Male',
        address: 'Kochi Fort area, Ernakulam, Kerala',
        medicalHistory: 'Post-CABG surgery (2022), Controlled BP',
        createdAt: now.subtract(const Duration(days: 8)),
      ),
      Patient(
        id: 'PAT-1008',
        name: 'Kavita Joshi',
        phone: '9920345678',
        age: 39,
        gender: 'Female',
        address: 'Shivaji Nagar, Pune',
        medicalHistory: 'Hypothyroidism (Eltroxin 50mcg)',
        createdAt: now.subtract(const Duration(days: 5)),
      ),
      Patient(
        id: 'PAT-1009',
        name: 'Deepak Deshmukh',
        phone: '9371098765',
        age: 41,
        gender: 'Male',
        address: 'Residency Road, Nagpur',
        medicalHistory: 'GERD, Acidity',
        createdAt: now.subtract(const Duration(days: 2)),
      ),
      Patient(
        id: 'PAT-1010',
        name: 'Meenakshi Sundaram',
        phone: '9444056789',
        age: 55,
        gender: 'Female',
        address: 'T. Nagar, Chennai',
        medicalHistory: 'Osteopenia, Hypertension',
        createdAt: now,
      ),
    ];
  }

  static List<QueueItem> getSampleTodayQueue(List<Patient> patients) {
    final now = DateTime.now();

    return [
      QueueItem(
        id: 'Q-101',
        patientId: patients[0].id,
        patientName: patients[0].name,
        patientPhone: patients[0].phone,
        tokenNumber: 1,
        timeAdded: now.subtract(const Duration(minutes: 65)),
        status: 'completed',
        chiefComplaint: 'Routine BP checkup and severe morning dizziness',
      ),
      QueueItem(
        id: 'Q-102',
        patientId: patients[1].id,
        patientName: patients[1].name,
        patientPhone: patients[1].phone,
        tokenNumber: 2,
        timeAdded: now.subtract(const Duration(minutes: 50)),
        status: 'completed',
        chiefComplaint: 'Throbbing headache and vomiting sensation',
      ),
      QueueItem(
        id: 'Q-103',
        patientId: patients[2].id,
        patientName: patients[2].name,
        patientPhone: patients[2].phone,
        tokenNumber: 3,
        timeAdded: now.subtract(const Duration(minutes: 35)),
        status: 'inConsultation',
        chiefComplaint: 'Fasting sugar test result evaluation & leg swelling',
      ),
      QueueItem(
        id: 'Q-104',
        patientId: patients[3].id,
        patientName: patients[3].name,
        patientPhone: patients[3].phone,
        tokenNumber: 4,
        timeAdded: now.subtract(const Duration(minutes: 20)),
        status: 'waiting',
        chiefComplaint: 'High fever (102°F) with body aches and dry cough',
      ),
      QueueItem(
        id: 'Q-105',
        patientId: patients[5].id,
        patientName: patients[5].name,
        patientPhone: patients[5].phone,
        tokenNumber: 5,
        timeAdded: now.subtract(const Duration(minutes: 10)),
        status: 'waiting',
        chiefComplaint: 'Shortness of breath and wheezing sound',
      ),
      QueueItem(
        id: 'Q-106',
        patientId: patients[8].id,
        patientName: patients[8].name,
        patientPhone: patients[8].phone,
        tokenNumber: 6,
        timeAdded: now.subtract(const Duration(minutes: 5)),
        status: 'waiting',
        chiefComplaint: 'Chest burning sensation after food',
      ),
    ];
  }

  static List<VisitRecord> getSampleVisits(List<Patient> patients) {
    final now = DateTime.now();

    return [
      // Today's Attended Visits
      VisitRecord(
        id: 'VIS-2001',
        patientId: patients[0].id,
        patientName: patients[0].name,
        date: now.subtract(const Duration(minutes: 40)),
        tokenNumber: 1,
        diagnosis: 'Essential Hypertension, Mild Orthostatic Hypotension',
        prescription: 'Tab Telmisartan 40mg OD morning\nTab Neurobion Forte 1 OD x 15 days',
        notes: 'BP recorded 148/92 mmHg. Advised low salt diet and daily 30 min brisk walk.',
        fee: 600.0,
        billId: 'BILL-3001',
      ),
      VisitRecord(
        id: 'VIS-2002',
        patientId: patients[1].id,
        patientName: patients[1].name,
        date: now.subtract(const Duration(minutes: 20)),
        tokenNumber: 2,
        diagnosis: 'Acute Migraine Episode',
        prescription: 'Tab Naproxen 500mg BD after food x 3 days\nTab Domperidone 10mg BD before food',
        notes: 'Advised rest in quiet dark room. Avoid caffeine and stress.',
        fee: 500.0,
        billId: 'BILL-3002',
      ),

      // Yesterday's Visits
      VisitRecord(
        id: 'VIS-2003',
        patientId: patients[4].id,
        patientName: patients[4].name,
        date: now.subtract(const Duration(days: 1, hours: 3)),
        tokenNumber: 1,
        diagnosis: 'Lumbar Spondylosis, Hyperlipidemia',
        prescription: 'Tab Atorvastatin 10mg HS\nCap Pregabalin 75mg HS x 10 days',
        notes: 'Referred for lower back physiotherapy. Lipid profile review next week.',
        fee: 750.0,
        billId: 'BILL-3003',
      ),
      VisitRecord(
        id: 'VIS-2004',
        patientId: patients[7].id,
        patientName: patients[7].name,
        date: now.subtract(const Duration(days: 1, hours: 5)),
        tokenNumber: 2,
        diagnosis: 'Primary Hypothyroidism',
        prescription: 'Tab Eltroxin 75mcg empty stomach morning',
        notes: 'TSH elevated at 7.2 mIU/L. Increased dosage from 50mcg to 75mcg.',
        fee: 500.0,
        billId: 'BILL-3004',
      ),

      // 3 Days Ago
      VisitRecord(
        id: 'VIS-2005',
        patientId: patients[2].id,
        patientName: patients[2].name,
        date: now.subtract(const Duration(days: 3, hours: 4)),
        tokenNumber: 1,
        diagnosis: 'Type 2 Diabetes, HbA1c 7.1%',
        prescription: 'Tab Metformin 500mg BD\nTab Teneligliptin 20mg OD',
        notes: 'Blood glucose controlled. Continue diabetic diet control.',
        fee: 500.0,
        billId: 'BILL-3005',
      ),
      VisitRecord(
        id: 'VIS-2006',
        patientId: patients[6].id,
        patientName: patients[6].name,
        date: now.subtract(const Duration(days: 3, hours: 2)),
        tokenNumber: 2,
        diagnosis: 'Post-CABG Cardiac Follow-up',
        prescription: 'Tab Aspirin 75mg OD\nTab Clopidogrel 75mg OD\nTab Metoprolol 25mg BD',
        notes: 'ECG normal sinus rhythm. Stable recovery.',
        fee: 1000.0,
        billId: 'BILL-3006',
      ),

      // 5 Days Ago
      VisitRecord(
        id: 'VIS-2007',
        patientId: patients[9].id,
        patientName: patients[9].name,
        date: now.subtract(const Duration(days: 5, hours: 6)),
        tokenNumber: 1,
        diagnosis: 'Osteopenia, Knee Joint Crepitus',
        prescription: 'Cap Shellcal 500 OD x 30 days\nSachet Vitamin D3 60k once weekly',
        notes: 'Advised quadriceps strengthening exercises.',
        fee: 500.0,
        billId: 'BILL-3007',
      ),

      // 7 Days Ago
      VisitRecord(
        id: 'VIS-2008',
        patientId: patients[3].id,
        patientName: patients[3].name,
        date: now.subtract(const Duration(days: 7, hours: 2)),
        tokenNumber: 1,
        diagnosis: 'Viral Upper Respiratory Infection',
        prescription: 'Tab Levocetirizine 5mg HS x 5 days\nSyrup Corex 5ml TDS',
        notes: 'Steam inhalation twice daily.',
        fee: 500.0,
        billId: 'BILL-3008',
      ),

      // 10 Days Ago
      VisitRecord(
        id: 'VIS-2009',
        patientId: patients[5].id,
        patientName: patients[5].name,
        date: now.subtract(const Duration(days: 10, hours: 4)),
        tokenNumber: 1,
        diagnosis: 'Acute Asthma Exacerbation',
        prescription: 'Asthalin Inhaler 2 puffs PRN\nTab Deriphyllin 150mg BD x 5 days',
        notes: 'Avoid cold climate exposure and dust masks outdoors.',
        fee: 600.0,
        billId: 'BILL-3009',
      ),
    ];
  }

  static List<Bill> getSampleBills(List<Patient> patients) {
    final now = DateTime.now();

    return [
      Bill(
        id: 'BILL-3001',
        billNumber: 'INV-20260820-001',
        patientId: patients[0].id,
        patientName: patients[0].name,
        patientPhone: patients[0].phone,
        date: now.subtract(const Duration(minutes: 40)),
        items: [
          BillItem(id: '1', description: 'Specialist Consultation Fee', quantity: 1, unitPrice: 600.0),
          BillItem(id: '2', description: 'Digital BP & Pulse Oxygen Check', quantity: 1, unitPrice: 100.0),
        ],
        subtotal: 700.0,
        discount: 100.0,
        tax: 0.0,
        totalAmount: 600.0,
        paymentStatus: 'Paid',
        paymentMethod: 'UPI',
      ),
      Bill(
        id: 'BILL-3002',
        billNumber: 'INV-20260820-002',
        patientId: patients[1].id,
        patientName: patients[1].name,
        patientPhone: patients[1].phone,
        date: now.subtract(const Duration(minutes: 20)),
        items: [
          BillItem(id: '1', description: 'Consultation Fee', quantity: 1, unitPrice: 500.0),
          BillItem(id: '2', description: 'Emergency Migraine Inoculation', quantity: 1, unitPrice: 350.0),
        ],
        subtotal: 850.0,
        discount: 50.0,
        tax: 0.0,
        totalAmount: 800.0,
        paymentStatus: 'Paid',
        paymentMethod: 'Cash',
      ),
      Bill(
        id: 'BILL-3003',
        billNumber: 'INV-20260819-001',
        patientId: patients[4].id,
        patientName: patients[4].name,
        patientPhone: patients[4].phone,
        date: now.subtract(const Duration(days: 1, hours: 3)),
        items: [
          BillItem(id: '1', description: 'Orthopedic Consultation Fee', quantity: 1, unitPrice: 750.0),
          BillItem(id: '2', description: 'Lumbosacral X-Ray Screen', quantity: 1, unitPrice: 600.0),
        ],
        subtotal: 1350.0,
        discount: 100.0,
        tax: 0.0,
        totalAmount: 1250.0,
        paymentStatus: 'Paid',
        paymentMethod: 'Card',
      ),
      Bill(
        id: 'BILL-3004',
        billNumber: 'INV-20260819-002',
        patientId: patients[7].id,
        patientName: patients[7].name,
        patientPhone: patients[7].phone,
        date: now.subtract(const Duration(days: 1, hours: 5)),
        items: [
          BillItem(id: '1', description: 'Endocrinology Consultation', quantity: 1, unitPrice: 500.0),
          BillItem(id: '2', description: 'Thyroid Profile Test (T3, T4, TSH)', quantity: 1, unitPrice: 450.0),
        ],
        subtotal: 950.0,
        discount: 50.0,
        tax: 0.0,
        totalAmount: 900.0,
        paymentStatus: 'Paid',
        paymentMethod: 'UPI',
      ),
      Bill(
        id: 'BILL-3005',
        billNumber: 'INV-20260817-001',
        patientId: patients[2].id,
        patientName: patients[2].name,
        patientPhone: patients[2].phone,
        date: now.subtract(const Duration(days: 3, hours: 4)),
        items: [
          BillItem(id: '1', description: 'Diabetology Consultation', quantity: 1, unitPrice: 500.0),
          BillItem(id: '2', description: 'HbA1c Glycated Hemoglobin Test', quantity: 1, unitPrice: 550.0),
        ],
        subtotal: 1050.0,
        discount: 50.0,
        tax: 0.0,
        totalAmount: 1000.0,
        paymentStatus: 'Paid',
        paymentMethod: 'UPI',
      ),
      Bill(
        id: 'BILL-3006',
        billNumber: 'INV-20260817-002',
        patientId: patients[6].id,
        patientName: patients[6].name,
        patientPhone: patients[6].phone,
        date: now.subtract(const Duration(days: 3, hours: 2)),
        items: [
          BillItem(id: '1', description: 'Cardiology Consultation Fee', quantity: 1, unitPrice: 1000.0),
          BillItem(id: '2', description: '12-Lead ECG Analysis', quantity: 1, unitPrice: 400.0),
          BillItem(id: '3', description: '2D Echocardiogram Screening', quantity: 1, unitPrice: 1500.0),
        ],
        subtotal: 2900.0,
        discount: 200.0,
        tax: 0.0,
        totalAmount: 2700.0,
        paymentStatus: 'Paid',
        paymentMethod: 'Card',
      ),
    ];
  }
}
